post http://localhost:4000/bank-api/user
Content-Type: application/json

{
  "username" : "Chinna", 
  "account_number" : 32123,
  "balance" : 1000
}

### Deposti
put http://localhost:4000/bank-api/deposit/12321
Content-Type:  application/json

{
  "username" : "Chaitanya", 
  "account_number" : 12321, 
  "balance" : 10000
}

### Withdrawl
put http://localhost:4000/bank-api/withdraw/12321/amount/10000
Content-Type:  application/json

{
  "username" : "Vasantha", 
  "account_number" : 12321, 
  "balance" : 1
}

###
put http://localhost:4000/bank-api/transfer/from/12321/to/32123
Content-Type: application/json

{
"balance" : 5000

}